const nachos = [
  {
    name: "Doritos Cheese Nachos - Pack of 2",
    brand: "Doritos",
    description:
      "Doritos is the spark that ignites you to be bold. Tooth Rattling Crunch & Intense Flavours that ignite you to Seize the Moment & Release your inner boldness. If you're up to the challenge, grab a bag of DORITOS Nacho Cheese tortilla chips and get ready for the experience. It's a bold experience in snacking and beyond",
    oldPrice: 60,
    price: 59,
    category: "Munchies",
    subCategory: "Nachos",
  },
  {
    name: "Bingo Mad Angles Pizza Nachos - Buy 3 Get 1 Free",
    brand: "Bingo Mad Angles",
    description:
      "These pizza flavoured nachos are brought all the way from Italy. With each bite of this deliciously crunchy snack you’ll be saying Mamma Mia! Made from a corn base, it is cooked with rice and flour. This uniquely textured triangular chips will give you a satisfying crunch with every bite. Dig into the pack to experience it's perfectly balanced taste.",
    oldPrice: 80,
    price: 60,
    category: "Munchies",
    subCategory: "Nachos",
  },
  {
    name: "Doritos Sweet Chilli Flavour Nachos",
    brand: "Doritos",
    description:
      "The great tasting bold snack with a perfect crunch and a spicy sweet chilli flavor. Doritos is the spark that ignites you to be bold. Tooth Rattling Crunch & Intense Flavours that ignite you to Seize the Moment & Release your inner boldness. If you’re up to the challenge, grab a bag of Doritos Sweet Chilli tortilla chips and get ready for the experience. It’s a bold experience in snacking and beyond.",
    oldPrice: 50,
    price: 45,
    category: "Munchies",
    subCategory: "Nachos",
  },
  {
    name: "Cornitos Nachos & Salsa Combo",
    brand: "Cornitos",
    oldPrice: 120,
    price: 114,
    category: "Munchies",
    subCategory: "Nachos",
  },
  {
    name: 'Salsalito Reguler 6" Taco Shells (12 pieces)',
    brand: "Salsalito",
    oldPrice: 180,
    price: 180,
    category: "Munchies",
    subCategory: "Nachos",
  },
  {
    name: "Cornitos Nacho Crisps & Dip Combo",
    brand: "Cornitos",
    oldPrice: 70,
    price: 67,
    category: "Munchies",
    subCategory: "Nachos",
  },
  {
    name: "Cornitos Peri Peri Nachos - Pack of 2",
    brand: "Cornitos",
    oldPrice: 40,
    price: 35,
    category: "Munchies",
    subCategory: "Nachos",
  },
  {
    name: "Cornitos Cheese & Herbs Nachos",
    brand: "Cornitos",
    description:
      "Experience the ultimate combination of cheese and herbs in Cornitos Cheese and Herbs flavour Nacho Crisps. Delectable flavours that no one can resist.",
    oldPrice: 90,
    price: 87,
    category: "Munchies",
    subCategory: "Nachos",
  },
  {
    name: "Bingo Mad Angles Cheese Nachos - Pack of 2",
    brand: "Bingo Mad Angles",
    description:
      "Bite into the cheesy goodness of bingo nacho cheese flavoured chips for a taste bud shattering crunch. Loaded with the goodness of corn and packed with a burst of cheesy flavour in every angle. Turn every snacking experience into a fiesta just burst open a pack and experience the delicious cheese,perfect triangular shape with the lip-smacking flavour - now in nachos,made from a corn base, the unique texture of bingo mad angles nachos adds to the crunchy fun,satisfy your snack cravings anytime, anywhere with yummy mad angles cheese nachos.",
    oldPrice: 40,
    price: 35,
    category: "Munchies",
    subCategory: "Nachos",
  },
  {
    name: "Makino Jalapeno Nacho Chips",
    brand: "Makino",
    oldPrice: 90,
    price: 72,
    category: "Munchies",
    subCategory: "Nachos",
  },
  {
    name: "Cornitos Sea Salt Nachos",
    brand: "Cornitos",
    description:
      "The lingering natural taste and the freshness of Sea Salt make for a fun snack even when added as an ingredient to your own recipe it’s simply irresistible. Sea Salt is a healthy snack as it is made from NON GMO Corn and cooked/baked using healthier Corn oil. Cornitos Nacho Crisps are also Gluten Free, Zero Cholesterol and Zero Transfat which makes them Guilt free Snacks.",
    oldPrice: 90,
    price: 90,
    category: "Munchies",
    subCategory: "Nachos",
  },
  {
    name: "Cornitos Crisps Peri Peri Nachos & Salsa Dip - Pack of 2",
    brand: "Cornitos",
    oldPrice: 120,
    price: 110,
    category: "Munchies",
    subCategory: "Nachos",
  },
  {
    name: "Cornitos Sizzlin Jalapeno Nachos",
    brand: "Cornitos",
    description:
      "Cornitos Nachos Sizzling Jalapeno have the simple heat of jalapeno peppers balanced with a fresh rounded flavour that will sizzle your taste Buds. These crispy tortilla chips are baked in healthy corn oil and have zero cholesterol. Enjoy the rich taste of Sizzling Jalapeno with your friends and family anywhere.",
    oldPrice: 90,
    price: 87,
    category: "Munchies",
    subCategory: "Nachos",
  },
  {
    name: "Makino Cheese Nachos",
    brand: "Makino",
    oldPrice: 90,
    price: 72,
    category: "Munchies",
    subCategory: "Nachos",
  },
  {
    name: "Cornitos Sizzlin Jalapeno Nachos + Coca-Cola Zero Sugar Soft Drink Combo",
    brand: "",
    oldPrice: 130,
    price: 122,
    category: "Munchies",
    subCategory: "Nachos",
  },
  {
    name: "Cornitos Sizzlin Jalapeno Nachos + Coca-Cola Soft Drink Combo",
    brand: "",
    oldPrice: 130,
    price: 123,
    category: "Munchies",
    subCategory: "Nachos",
  },
  {
    name: "Cornitos Sizzlin Jalapeno Nachos + Thums Up Soft Drink (750 ml) Combo",
    brand: "",
    oldPrice: 130,
    price: 123,
    category: "Munchies",
    subCategory: "Nachos",
  },
  {
    name: "Cornitos Sizzlin Jalapeno Nachos + Red Bull Energy Drink (250 ml) Combo",
    brand: "",
    oldPrice: 215,
    price: 211,
    category: "Munchies",
    subCategory: "Nachos",
  },
  {
    name: "Thums Up Soft Drink (2.25 l) + Cornitos Nachos & Salsa Combo Combo",
    brand: "",
    oldPrice: 537,
    price: 491,
    category: "Munchies",
    subCategory: "Nachos",
  },
  {
    name: "Red Bull Energy Drink (4 x 250 ml) + Cornitos Nachos & Salsa Combo Combo",
    brand: "",
    oldPrice: 720,
    price: 666,
    category: "Munchies",
    subCategory: "Nachos",
  },
];

export default nachos;
