const bread = [
  {
    name: "Britannia 100% Whole Wheat Bread",
    brand: "Britannia",
    description:
      "Made from 100% whole wheat grains, Britannia's Whole Wheat Bread is a good source of fibre and essential nutrients. Soft and delicious, enjoy toasted bread with tea or roast it on pan for making crunchy croutons.",
    oldPrice: 55,
    price: 55,
    category: "Dairy, Bread & eggs",
    subCategory: "Bread",
  },
  {
    name: "Britannia Milk Bread",
    brand: "Britannia",
    oldPrice: 50,
    price: 50,
    category: "Dairy, Bread & eggs",
    subCategory: "Bread",
  },
  {
    name: "Britannia Healthy Slice White Bread",
    brand: "Britannia",
    description:
      "Baked with the goodness and rich flavour, Britannia Healthy Slice Bread comes enriched with essential vitamins. Soft, wholesome and fluffy, it is perfect from crunchy toasts to hearty vegetable sandwiches.",
    oldPrice: 50,
    price: 50,
    category: "Dairy, Bread & eggs",
    subCategory: "Bread",
  },
  {
    name: "Modern Multigrain Bread",
    brand: "Modern",
    oldPrice: 60,
    price: 60,
    category: "Dairy, Bread & eggs",
    subCategory: "Bread",
  },
  {
    name: "Britannia Brown Bread",
    brand: "Britannia",
    description:
      "Enriched with fibre, Britannia Brown Bread is soft, fluffy and wholesome. Made with wholewheat flour, it has an amazing flavour and soft crust, simply ideal for making sandwiches and toasts.",
    oldPrice: 55,
    price: 55,
    category: "Dairy, Bread & eggs",
    subCategory: "Bread",
  },
  {
    name: "Wingreens Farms Multigrain Baked Flat Bread Sticks",
    brand: "Wingreens Farms",
    oldPrice: 150,
    price: 128,
    category: "Dairy, Bread & eggs",
    subCategory: "Bread",
  },
  {
    name: "The Baker's Dozen 100% Wholewheat Multigrain Loaf",
    brand: "The Baker's Dozen",
    description:
      "The perfect daily bread, the multigrain loaf is made with 100% whole wheat (atta), and no added maida. Engrained with four different grains (sesame, flax, pumpkin, and sunflower seeds), the multigrain bread is made without any added preservatives or chemicals, and packed using FreshLock packaging technology that retains its oven baked freshness",
    oldPrice: 65,
    price: 65,
    category: "Dairy, Bread & eggs",
    subCategory: "Bread",
  },
  {
    name: "The Baker's Dozen Pita Bread (100% Whole Wheat)",
    brand: "The Baker's Dozen",
    oldPrice: 85,
    price: 85,
    category: "Dairy, Bread & eggs",
    subCategory: "Bread",
  },
  {
    name: "Nilgiris Whole Wheat Brown Bread",
    brand: "Nilgiris",
    oldPrice: 55,
    price: 55,
    category: "Dairy, Bread & eggs",
    subCategory: "Bread",
  },
  {
    name: "Nilgiris Whole Wheat Bread",
    brand: "Nilgiris",
    oldPrice: 55,
    price: 55,
    category: "Dairy, Bread & eggs",
    subCategory: "Bread",
  },
];
export default bread;
